# This storage class uses the standard GCE persistent disks
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: general
provisioner: kubernetes.io/aws-ebs
parameters:
  type: io1
  iopsPerGB: "10"
  fsType: ext4